### ISSUE TITLE
Cost

### ISSUE THREAD

**Issue by davebulaval** [DougTrajano/mlflow-server#103]
Hi,

What is the usual monthly cost of this infra?

**Comment by DougTrajano** [comment]
Hello buddy!

Approximately USD 9, almost all involved costs is related to RDS Database.

We are not able to use Aurora Serverless that allows us to suspend a database in times with no traffic because the App Runner is not instantiated in the same VPC. This is a requested feature in AWS AppRunner Roadmap. With that, the costs should be reduced for +- USD 4/mo.

Tks,
Douglas

**Comment by davebulaval** [comment]
I personally prefer wandb, so I will try next week to change your work and propose a PR with a wandb version along with the mlflow one.

**Comment by DougTrajano** [comment]
Interesting, I didn't know [wandb](https://github.com/wandb).

If I understood, wandb is a SaaS solution and there's no self-hosted option. How we can integrate wandb with this work?

**Comment by davebulaval** [comment]
No, there is a [local self-hosted version](https://github.com/wandb/local). Wandb, is way more interesting for visualization of graphics, comparing runs and metrics and else. It's really a complete one but that mother fucking [terraform](https://github.com/wandb/local/tree/main/terraform/aws) script is just not working and is leveraging a load balancer and so much stuff that it cost 10$ a day.
