### ISSUE TITLE
Issue after launching APPrunner

### ISSUE THREAD

**Issue by ogreyesp** [DougTrajano/mlflow-server#95]
Hello

I'm very interested in installing MLFLOW in AWS free tier, so I have followed in detail all the described steps in your blog. I'm very new in both MLFLOW and AWS.

After following all the steps of your blog, I got the following error when I tried to access to the MLFLOW UI.

![image](https://user-images.githubusercontent.com/17004570/147876147-b7c30fbc-d7d4-4bee-b4e5-fc0a4bb0a01e.png)

What could be the problem?

Thanks in advance!

**Comment by DougTrajano** [comment]
Hey buddy! Thank you for using it. I'm very happy about that.

Probably, the VPC used by our RDS Database doesn't allow traffic outside VPC for your RDS. It is required because the App Runner uses a VPC provided by AWS (hidden for us).

You can take a look at this issue https://github.com/DougTrajano/mlflow-server/issues/28

You can change your VPC Security Groups to allow external traffic.

**Comment by ogreyesp** [comment]
Hi, Thank you for your response,

I have followed the steps described [here](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html), but the problem still persists.

**Comment by DougTrajano** [comment]
> Hi, Thank you for your response,
> 
> I have followed the steps described [here](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html), but the problem still persists.

Could you post here the AppRunner's logs? Probably we will find the root cause there. :)
